# Desafio: leyendo datos con multiples parametros

### recursos: datos_sus.csv
de la pagina: https://datasus.saude.gov.br/informacoes-de-saude-tabnet/

In [4]:
import pandas as pd
import chardet as chardet

1. Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.

In [ ]:
datos = pd.read_csv('datos_sus.csv') #error de encoding

In [28]:
#abrir con chardet con with open
with open('datos_sus.csv', 'rb') as f:
    print(chardet.detect(f.read()))

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

2. La codificación del archivo es ISO-8859-1.
3. Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.

In [37]:
datos = pd.read_csv('datos_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3)
datos.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

4. Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.
5. Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.

In [38]:
datos = pd.read_csv('datos_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter=9, engine='python')
datos.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

### desafio 2: leyendo datos de otro link
archivo emisiones_carbono_mundo.xlsx usado en google sheets

In [2]:
sheet_id = '1fkVoRTYmvVjCCLIalVw13EdRwiGXkRd0A3L5fHux1gk'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [7]:
datos_carbono_sheets = pd.read_csv(url)

In [8]:
datos_carbono_sheets.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432

In [9]:
#almaceno el url sheet en csv
datos_carbono_sheets.to_csv('datos_emisiones_co2.csv', index=False)

### Obteniendo archivos JSON de APIs

In [14]:
import requests
import json

In [15]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [16]:
resultado = json.loads(datos_frutas.text)

In [18]:
resultado_json = pd.DataFrame(resultado)

In [20]:
resultado_json.head(5)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."

### Desafio3: normalizar el JSON obtenido de la API

In [21]:
resultado_normalizado = pd.json_normalize(resultado_json['nutritions'])

In [22]:
resultado_normalizado

    calories    fat  sugar  carbohydrates  protein
0         81   0.00  18.00          18.00     0.00
1         29   0.40   5.40           5.50     0.80
2         96   0.20  17.20          22.00     1.00
3         74   0.20   2.60           3.90     0.90
4         57   0.10  10.00          15.00     0.40
5        147   5.30   6.75          27.10     1.50
6         40   0.40   4.50           9.00     1.30
7         50   0.34   5.74          11.30     0.75
8         61   0.50   9.00          15.00     1.10
9         66   0.44  15.00          17.00     0.80
10        50   0.12   9.85          13.12     0.54
11        74   0.30  16.00          19.00     0.80
12        44   0.60   0.00          10.00     0.90
13        97   0.70  11.20          22.40     2.20
14        46   0.28   9.92          11.40     0.70
15        43   0.20   8.20           8.30     1.00
16        21   0.10   6.40           3.10     0.40
17        53   0.70   4.40          12.00     1.20
18        30   0.20   6.00           8.00     0.60
19        29   0.30   2.50           9.00     1.10
20        60   0.38  13.70          15.00     0.82
21        29   0.40   5.40           5.50     0.00
22        52   0.40  10.30          11.40     0.30
23        68   1.00   9.00          14.00     2.60
24        15   0.10   3.20           3.90     0.50
25        34   0.00   8.00           8.00     0.00
26        45   0.40   9.10           8.30     0.00
27        36   0.40   3.00           7.00     1.00
28        25   0.10   1.70           8.40     0.30
29        83   1.20  13.70          18.70     1.70
30        60   1.50   8.00           9.00     9.00
31        69   0.16  16.00          18.10     0.72
32        43   0.39   8.10           9.80     1.44
33        44   0.40   3.00           8.00     0.60
34       160  14.66   0.66           8.53     2.00
35        61   0.50   8.90          14.60     1.14
36        46   0.10   4.00          12.20     0.40
37        50   0.30   8.00          12.00     1.00
38        39   0.25   8.40           9.50     0.90
39        95   0.00  19.10          23.20     1.72
40        44   1.26   0.50           7.56     1.78
41       628  61.00   4.30          17.00    15.00
42        37   0.00   8.50           9.67     0.82
43        73   0.58  16.11          17.91     0.41
44        25   0.30   3.30           4.60     1.10
45        70   0.20  13.00          19.00     0.60
46        39   0.30   4.40           5.80     0.50
47        92   0.29   3.40          19.10     1.50
48        47   0.30   8.10           9.60     1.20

### Desafio3: leer una tabla de una pagina web

In [25]:
import pandas as pd

In [35]:
url = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n'
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)

tablas = pd.read_html(response.text)
            
leer_poblacion_html = tablas[0]

leer_poblacion_html.head()

/tmp/ipykernel_9895/3179097680.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(response.text)

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/7/2025[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,India,1 417 492 000,1754,090,12 692 000,1547,78,1 417 492 000,1/07/2025,A,web.archive.org
1,2,China[12]​,1 407 934 000,1743,-005,-1 390 000,-,-,1 408 280 000,31/12/2024,E,www.stats.gov.cn
2,3,Estados Unidos,342 181 000,424,061,2 084 000,254,114,343 186 000,20/01/2026,R,www.census.gov
3,4,Indonesia,284 447 000,352,107,3 043 000,371,65,284 438 782,30/06/2025,E,www.bps.go.id
4,5,Pakistán,256 204 000,317,256,6 567 000,800,27,241 499 431,1/03/2023,C,www.pbs.gov.pk

### Desafio: manipulando una base de datos
archivo: clientes_banco_practica.csv

In [9]:
from sqlalchemy import create_engine, text, inspect
from sqlalchemy.exc import SQLAlchemyError
import pandas as pd

In [3]:
#1 --------- Crear la base de datos local con la biblioteca SQLAlchemy. -----------
engine = create_engine('sqlite:///:memory:')

In [4]:
#2 --------- Escribir los datos del archivo CSV en esta base de datos local. -----------
archivo = 'clientes_banco_practica.csv' #almaceno en variable el nombre del archivo
datos = pd.read_csv(archivo) #leo el archivo csv y almaceno el dataframe en datos
datos.to_sql('clientes', engine, index=False) #escribo el df en la base de datos

438463

In [8]:
query = "SELECT * FROM clientes WHERE Categoria_de_renta='Empleado';"
clientes = pd.read_sql(sql=text(query), con=engine.connect())
clientes

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [10]:
#3 --------- Realizar tres actualizaciones en la base de datos: -----------
#- Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
query = "UPDATE clientes SET Rendimiento_anual=300000 WHERE ID_Cliente=6840104"

try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print(f"Registros actualizados: {r_set.rowcount}")

Registros actualizados: 1

In [12]:
query = "SELECT * FROM clientes WHERE ID_Cliente=6840104;"
pd.read_sql(sql=text(query), con= engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,300000.0,0,Casa/Departamento propio

In [13]:
#- Eliminar el registro de cliente ID 5008809, 
# ya que esta persona ya no tiene cuenta en la institución financiera.

query = "DELETE FROM clientes WHERE ID_Cliente=5008809"

try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print(f"Registros actualizados: {r_set.rowcount}")

Registros actualizados: 1

In [14]:
query = "SELECT * FROM clientes WHERE ID_Cliente=5008809;"
pd.read_sql(sql=text(query), con= engine.connect())

Empty DataFrame
Columns: [ID_Cliente, Edad, Grado_estudio, Estado_civil, Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, Rendimiento_anual, Tiene_carro, Vivienda]
Index: []

-Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:  
    ID_cliente: 6850985  
    Edad: 33  
    Grado_estudio: Doctorado  
    Estado_civil: Soltero  
    Tamaño_familia: 1  
    Categoria_de_renta: Empleado  
    Ocupacion: TI  
    Años_empleado: 2  
    Rendimiento_anual: 290000  
    Tiene_carro: 0  
    Vivienda: Casa/Departamento propio

In [15]:

query = """INSERT INTO clientes 
            (
                ID_Cliente, Edad, Grado_estudio, Estado_civil, Tamaño_familia, Categoria_de_renta, 
                Ocupacion, Años_empleado, Rendimiento_anual, Tiene_carro, Vivienda
            ) VALUES
            (
                6850985, 33, 'Doctorado', 'Soltero', 1, 'Empleado', 
                'TI', 2, 290000, 0, 'Casa/Departamento propio'
            )
            """

try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print(f"Registros ingresados: {r_set.rowcount}")

Registros ingresados: 1

In [16]:
query = "SELECT * FROM clientes WHERE ID_Cliente=6850985;"
pd.read_sql(sql=text(query), con= engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,6850985,33,Doctorado,Soltero,1,Empleado,TI,2,290000.0,0,Casa/Departamento propio